using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;


namespace Assignment4
{
    public class DataService
    {
        public List<Category> GetCategories()
        {
            using (var db = new NorthwindContext())
            {
                return db.Categories
                    .OrderBy(c => c.Id)
                    .ToList();
            }
        }

        public Category CreateCategory(string name, string description)
        {
            using (var db = new NorthwindContext())
            {

                var categoriesLength = db.Categories.Count();
                var category = new Category
                {
                    Id = categoriesLength + 1,
                    Name = name,
                    Description = description
                };

                db.Categories.Add(category);
                db.SaveChanges();

                return category; // The Id will be automatically generated by the database
            }
        }

        public bool DeleteCategory(int id)
        {
            using (var db = new NorthwindContext())
            {
                var category = db.Categories.Find(id);
                if (category == null)
                    return false;

                db.Categories.Remove(category);
                db.SaveChanges();
                return true;
            }
        }

        public Category GetCategory(int id)
        {
            using (var db = new NorthwindContext())
            {
                return db.Categories.Find(id);
            }
        }

        public bool UpdateCategory(int id, string name, string description)
        {
            using (var db = new NorthwindContext())
            {
                var category = db.Categories.Find(id);
                if (category == null)
                    return false;

                category.Name = name;
                category.Description = description;

                db.SaveChanges();
                return true;
            }
        }

        public Product GetProduct(int id)
        {
            using (var db = new NorthwindContext())
            {
                return db.Products
                    .Include(p => p.Category) // Include the related Category
                    .FirstOrDefault(p => p.Id == id);
            }
        }

     

     


        public List<ProductByCategory> GetProductByCategory(int categoryId)
        {
            using (var db = new NorthwindContext())
            {
                return db.Products
                    .Include(p => p.Category)
                    .Where(p => p.CategoryId == categoryId)
                    .OrderBy(p => p.Id)
                    .Select(p => new ProductByCategory
                    {
                        Name = p.Name,
                        CategoryName = p.Category.Name
                    })
                    .ToList();
            }
        }



        public List<ProductByName> GetProductByName(string name)
        {
            using (var db = new NorthwindContext())
            {
                return db.Products
                    .Where(p => p.Name.ToLower().Contains(name.ToLower()))
                    .OrderBy(p => p.Id)
                    .Select(p => new ProductByName
                    {
                        ProductName = p.Name  // Only map what the test checks
                    })
                    .ToList();
            }
        }




    }
}


